---
# tasks file for influxdb
  - name: Install Influxdb
    yum: name=influxdb state=present
  
  - name: Copy InfluxDB configuration
    template: src=influxdb.conf.j2 dest=/etc/influxdb/influxdb.conf

  - name: Start InfluxDB 
    service: name=influxdb state=restarted enabled=true
