---
# tasks file for consul
- name:  Verify Docker-engine
  yum: name=docker state=present
  become: true

- name: verify docker.py installation
  yum: name=docker-python state=present
  become: true

- name: start docker engine
  service: name=docker state=started enabled=yes
  become: true

- name: verify consul container is running
  docker:
     name: consul
     image: consul
     state: started
  become: true
