- name: Verify Instances
  hosts: openstack
  
  roles:
   - openstack

- name: Common
  hosts: all

  roles:
     - common
     - sensu-agent
     - telegraf
     - docker
     

- name: consul server setup
  hosts: consul
 
  roles:
    - consul

- name: Kafka Servers
  hosts: kafka

  roles:
    - kafka

- name: Database Servers
  hosts: db
 
  roles:
    - influxdb

- name: UI servers
  hosts: ui
 
  roles:
    - chronograf

- name: Sensu
  hosts: sensu

  roles:
    - sensu-server

- name: k8s
  hosts: k8s
 
  roles:
   - k8s
