- name: Verify Instances
  hosts: openstack
  
  roles:
#   - openstack

- name: Common
  hosts: all

  roles:
     - common
     - telegraf
     - docker

- name: consul server setup
  hosts: consul
 
  roles:
    - consul

- name: Kafka Servers
  hosts: kafka

  roles:
    - kafka
