- name: Verify Instances
  hosts: openstack
  
  roles:
#    - openstack

- name: Common
  hosts: consul

  roles:
     - common

- name: consul server setup
  hosts: consul
 
  roles:
    - consul
    
