---
# tasks file for k8s

- name: Install Kubernetes Repo
  yum_repository:
    name: k8s
    description: Kubernetes
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
    gpgcheck: no

- name: Install Kubernetes 
  yum: name=kubernetes state=present

- name: Install etcd
  yum: name=etcd state=present

- name: Copy Kubernetes configuration file
  template: src=k8s_config.j2 dest=/etc/kubernetes/config

- name: Disable FirewallD service
  service: name=firewalld state=stopped enabled=false
  ignore_errors: true

- name: Disabe iptables-services
  service: name=iptables-services state=stopped enabled=false
  ignore_errors: true

- name: Copy Kubelet configuration
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet

- name: Copy EtcD on master
  template: src=etcd_conf.j2 dest=/etc/etcd/etcd.conf
  when: inventory_hostname == "k8s-01"

- name: Copy API server on master
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  when: inventory_hostname == "k8s-01"

- name: Start EtcD on Master
  service: name=etcd state=restarted enabled=true
  when: inventory_hostname == "k8s-01"

- name: Start kube-apiserver 
  service: name=kube-apiserver state=restarted enabled=true
  when: inventory_hostname == "k8s-01"

- name: Start kube-controller-manager
  service: name=kube-controller-manager state=restarted enabled=true
  when: inventory_hostname == "k8s-01"

- name: Start kube-scheduler
  service: name=kube-scheduler state=restarted enabled=true
  when: inventory_hostname == " k8s-01"


- name: Restart kube-proxy
  service: name=kube-proxy state=restarted enabled=true
  when: inventory_hostname == "k8s-02"

- name: Restart kubelet
  service: name=kubelet state=restarted enabled=true
  when: inventory_hostname == "k8s-02"

