---
# tasks file for openstack
- name: Ensure we have a instance
  os_server: 
      state: present
      name: "{{ item.name }}"
      image: 59c75822-4c5f-466a-8d98-825bf0e3e1c1
      key_name: mesterlab
      timeout: 200
      flavor: "{{ item.flavor }}"
      security_groups: default
      auto_ip: yes
  with_items: "{{ instances }}"

- name: update Openstack_Facts
  os_server_facts:

