---
# tasks file for common

  - name: Disable SELinux
    selinux: state=disabled

  - name: enable epel repos
    yum: name=epel-release state=present

  - name: clean yum repos
    command: /bin/yum clean all

  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']

  - name: "remote requiretty"
    lineinfile: dest=/etc/sudoers line="Defaults    requiretty" state=absent
    tags: tty

  - name: install Java 1.8 
    yum: name=java-1.8.0-openjdk state=present

  - name: install pip
    yum: name=python-pip state=present

  - name: install python-consul
    pip:
      name: python-consul
      state: present

  - name: Register IP address with Consul
    consul_kv:
       host: ns1
       state: present
       key: "{{ansible_hostname}}/ip"
       value: "{{ansible_default_ipv4}}"
       validate_certs: False

  - name: Register Host OS with Consul
    consul_kv:
       host: ns1
       state: present
       key: "{{ ansible_hostname }}/OS"
       value: "{{ ansible_distribution }}"
       validate_certs: False


