---
# tasks file for common

  - name: Disable SELinux
    selinux: state=disabled

  - name: enable epel repos
    yum: name=epel-release state=present

  - name: install Java 1.8 
    yum: name=java-1.8.0-openjdk state=present

