---
# defaults file for openstack
instances:
 - name: ns1
   flavor: 3
 - name: ns2
   flavor: 3
 - name: sensu
   flavor: 3
 - name: kafka-01
   flavor: 3
 - name: db
   flavor: 3
 - name: k8s-01
   flavor: 4
 - name: k8s-02
   flavor: 4
 - name: k8s-master
   flavor: 2

